version: '3.8'

services:
  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: samsam98
      MYSQL_DATABASE: itemsdb
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  auth:
    build: auth/.
    ports:
      - "4000:4000"
    depends_on:
    - "auth-db"
  event-bus:
    build: event-bus/.
    ports:
      - "4001:4001"
  items:
    build: items/.
    ports:
      - "4002:4002"
    depends_on:
    - "items-db"
  moderation:
    build: moderation/.
    ports:
      - "4004:4004"
    depends_on:
      - "moderation-db"
  items-db:
    build: items_db/.
    ports:
      - "4007:4007"
    links:
    - mysql-development:db
    depends_on:
      - mysql-development
  auth-db:
    build: auth_db/.
    ports:
      - "4008:4008"
